"""empty message

Revision ID: faf233e7833d
Revises: 82a42fe74713
Create Date: 2020-03-15 16:04:10.095712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf233e7833d'
down_revision = '82a42fe74713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorturls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortkey', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shorturls_shortkey'), 'shorturls', ['shortkey'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shorturls_shortkey'), table_name='shorturls')
    op.drop_table('shorturls')
    # ### end Alembic commands ###
